name: RELEASE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ gh-pages, main ]
  #schedule:
  #  - cron:  '0 * * * 1'
  #  - cron:  '50 17 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: AUTOMATIZACIÃ“N
      run: |
        echo "Vamos Bien"
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo "Vamos a lo importante..."
        python automatizacion.py

    - uses: stefanzweifel/git-auto-commit-action@v2
      with:
        commit_message: "Actualizacion"
        branch: gh-pages
        # Optional glob pattern of files which should be added to the commit
        #file_pattern: /
        # Optional local file path to the repository
        repository: .

        # Optional commit user and author settings
        commit_user_name: Actions Bot
        commit_user_email: lmonsalve22@gmail.com
        commit_author: DataIntelligence BOT <lmonsalve22@gmail.com>
        push_options: '--force'
    - uses: actions/checkout@v3
      - name: Install and Build ðŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm ci
          npm run build

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build